### ISSUE TITLE
Unable deploy to rancher

### ISSUE THREAD

**Issue by Barlog951** [cdrx/rancher-gitlab-deploy#18]
Hi 

I have [this error ](https://www.dropbox.com/s/rdrh0ly0ypcu1ox/Screenshot%202017-05-04%2023.04.29.png?dl=0) on my gitlab deploy pipeline 

this is my deploy script 
```
image: docker:latest
 services:
  - docker:dind
.......


deploy_devel:
  stage: deploy
  tags:
      - docker
  environment:
    name: develop
  image: cdrx/rancher-gitlab-deploy
  script:
    - upgrade --rancher-url $URL --rancher-key $MASTER_ACCESS_KEY --rancher-secret $MASTER_SECRET_KEY --stack testing --service web
```

Any idea why this happens?

Thanks

**Comment by cdrx** [comment]
Do you have a before_script with 'docker info' in it? That command won't work in the rancher-gitlab-deploy container

**Comment by Barlog951** [comment]
Hi

thanks for the advice, now deploy work good, but sometimes rancher not pull a new image ...

**Comment by cdrx** [comment]
Glad its working (mostly)! I would file a bug with Rancher if it doesn't always pull the new image.

**Comment by patrickrb** [comment]
I'm having the same issue consistently.  For some reason, the deploy stage of the pipeline doesnt seem to have access to docker.

**Comment by cdrx** [comment]
What does your gitlab-ci.yml look like?

**Comment by patrickrb** [comment]
Here is my gitlab-ci-yml (truncated the rancher API vars)

```
image: docker:latest

services:
  - docker:dind
  
before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

build-master:
  stage: build
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE" .
    - docker push "$CI_REGISTRY_IMAGE"
  only:
    - master

build:
  stage: build
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" .
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
  except:
    - master
    
deploy:
  stage: deploy
  image: cdrx/rancher-gitlab-deploy
  script:
    - upgrade --environment production --stack soundboardr --service soundboardr-frontend
```
