### ISSUE TITLE
Upgrade sidekick

### ISSUE THREAD

**Issue by ghost** [cdrx/rancher-gitlab-deploy#3]
Hello.
Thnx for your utility.
But I have a question - how to upgrade only a sidekick? I'm trying to set sidekick name to --new-image, but got the error like this: "Error: Unable to find a service called 'code', does it exist in Rancher?".

Example of stack:
```
php-fpm:
  labels:
    io.rancher.sidekicks: code
    io.rancher.container.pull_image: always
  image: gitlab.local:4567/integrations/docker:php-fpm
  volumes_from:
  - code
code:
  labels:
    io.rancher.container.pull_image: always
    io.rancher.container.start_once: 'true'
  image: gitlab.local:4567/integrations/code:dev
```
