### ISSUE TITLE
Can not update containers. Line 64: Upgrade: command not found

### ISSUE THREAD

**Issue by tbublik** [cdrx/rancher-gitlab-deploy#31]
Hi, your job is awesome, unfortunately I can not make it work. When the deploy stage comes it throws this error "Line 64: **Upgrade**: Command not found. Exit status 1". I provided all secrets to GitLab secret variables: the environment API keys, URL (http://IP_address:8080). My gitlab-ci.yml is below

```
image: docker:latest
services:
  - docker:dind
  
stages:
  - build
  - deploy

variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE:webapp_v1.$CI_BUILD_ID

build:
  stage: build
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG

deploy:
  stage: deploy
  image: cdrx/rancher-gitlab-deploy
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - upgrade --new-image $CI_REGISTRY_IMAGE:webapp_v1.$CI_BUILD_ID --stack RoR-web-application --service rails

```
Thanks,
Cheers
