### ISSUE TITLE
Upgrade multiple containers in parallel

### ISSUE THREAD

**Issue by cryptiklemur** [cdrx/rancher-gitlab-deploy#36]
Would be super nice if we could update multiple containers in parallel. I know there are tools that let you do that, but none of these tools are installed on the image, afaik

**Comment by cdrx** [comment]
You can do that in your .gitlab-ci.yml file — if you define multiple steps in the same (deploy) stage they will run concurrently

**Comment by cdrx** [comment]
If defined like this:

```
deploy-web:
  stage: deploy
  image: cdrx/rancher-gitlab-deploy
  script:
    - upgrade --service web

deploy-database:
  stage: deploy
  image: cdrx/rancher-gitlab-deploy
  script:
    - upgrade --service db
```

these will run in parallel, as long as you've got a runner with concurrency > 1
